-- v1: create_tables.sql
-- Only basic employees table (no relations yet)

CREATE TABLE employees (
  emp_id     NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  name       VARCHAR2(200) NOT NULL,
  dob        DATE,
  salary     NUMBER(18,2) DEFAULT 0,
  hire_date  DATE DEFAULT SYSDATE
);
