-- Project : Employee Management System
-- Version : v2 (Departments + Relations)
-- File    : create_departments.sql
-- Purpose : Create departments master table

CREATE TABLE departments (
  dept_id    NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  dept_name  VARCHAR2(100) NOT NULL
);
