-- Project : Employee Management System
-- Version : v3 (Triggers + Audit + Validation)
-- File    : create_employee_audit.sql
-- Purpose : Audit employee changes

CREATE TABLE employee_audit (
  audit_id     NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  emp_id       NUMBER,
  action_type  VARCHAR2(10), -- INSERT / UPDATE / DELETE
  old_salary   NUMBER,
  new_salary   NUMBER,
  action_date  DATE DEFAULT SYSDATE
);
